baseURL = 'https://panaritj.github.io/'
languageCode = 'en-us'
title = "Panarit's blog"
theme = 'PaperMod'

[params]
    defaultTheme = "light" # Forces the white background look
    ShowReadingTime = true


[params.homeInfoParams]
    Title = "Hi, my name is Panarit Jahiri."
    Content = """
    I have been working with technology in one way or another since I was a kid. Currently, I am based in Berlin, working as an engineer in the AI Core unit at SAP, focusing on Generative AI.
    
    This is where I document my thoughts on engineering, "philosophy", complex concepts, and building software. I am all about optimizing my computer workflow. 
    
    I also do quite a bit of photography on the side. A bit of everything: landscape, street, abstract. You can find my visual work on [Instagram](https://www.instagram.com/panarit.visuals).
    
    *Opinions are my own.*
    """

[[menu.main]]
    identifier = "archives"
    name = "Posts"
    url = "/archives/"
    weight = 10
